const bla = {
  count: 113,
  results: [
    { index: "acolyte", name: "Acolyte", url: "/api/monsters/acolyte" },
    { index: "ape", name: "Ape", url: "/api/monsters/ape" },
    {
      index: "awakened-shrub",
      name: "Awakened Shrub",
      url: "/api/monsters/awakened-shrub",
    },
    { index: "axe-beak", name: "Axe Beak", url: "/api/monsters/axe-beak" },
    { index: "baboon", name: "Baboon", url: "/api/monsters/baboon" },
    { index: "badger", name: "Badger", url: "/api/monsters/badger" },
    { index: "bandit", name: "Bandit", url: "/api/monsters/bandit" },
    { index: "bat", name: "Bat", url: "/api/monsters/bat" },
    {
      index: "black-bear",
      name: "Black Bear",
      url: "/api/monsters/black-bear",
    },
    { index: "blink-dog", name: "Blink Dog", url: "/api/monsters/blink-dog" },
    {
      index: "blood-hawk",
      name: "Blood Hawk",
      url: "/api/monsters/blood-hawk",
    },
    { index: "boar", name: "Boar", url: "/api/monsters/boar" },
    { index: "camel", name: "Camel", url: "/api/monsters/camel" },
    { index: "cat", name: "Cat", url: "/api/monsters/cat" },
    {
      index: "cockatrice",
      name: "Cockatrice",
      url: "/api/monsters/cockatrice",
    },
    { index: "commoner", name: "Commoner", url: "/api/monsters/commoner" },
    {
      index: "constrictor-snake",
      name: "Constrictor Snake",
      url: "/api/monsters/constrictor-snake",
    },
    { index: "crab", name: "Crab", url: "/api/monsters/crab" },
    { index: "crocodile", name: "Crocodile", url: "/api/monsters/crocodile" },
    { index: "cultist", name: "Cultist", url: "/api/monsters/cultist" },
    {
      index: "darkmantle",
      name: "Darkmantle",
      url: "/api/monsters/darkmantle",
    },
    {
      index: "deep-gnome-svirfneblin",
      name: "Deep Gnome (Svirfneblin)",
      url: "/api/monsters/deep-gnome-svirfneblin",
    },
    { index: "deer", name: "Deer", url: "/api/monsters/deer" },
    {
      index: "draft-horse",
      name: "Draft Horse",
      url: "/api/monsters/draft-horse",
    },
    { index: "dretch", name: "Dretch", url: "/api/monsters/dretch" },
    { index: "drow", name: "Drow", url: "/api/monsters/drow" },
    {
      index: "dust-mephit",
      name: "Dust Mephit",
      url: "/api/monsters/dust-mephit",
    },
    { index: "eagle", name: "Eagle", url: "/api/monsters/eagle" },
    { index: "elk", name: "Elk", url: "/api/monsters/elk" },
    {
      index: "flying-snake",
      name: "Flying Snake",
      url: "/api/monsters/flying-snake",
    },
    {
      index: "flying-sword",
      name: "Flying Sword",
      url: "/api/monsters/flying-sword",
    },
    { index: "frog", name: "Frog", url: "/api/monsters/frog" },
    {
      index: "giant-badger",
      name: "Giant Badger",
      url: "/api/monsters/giant-badger",
    },
    { index: "giant-bat", name: "Giant Bat", url: "/api/monsters/giant-bat" },
    {
      index: "giant-centipede",
      name: "Giant Centipede",
      url: "/api/monsters/giant-centipede",
    },
    {
      index: "giant-crab",
      name: "Giant Crab",
      url: "/api/monsters/giant-crab",
    },
    {
      index: "giant-fire-beetle",
      name: "Giant Fire Beetle",
      url: "/api/monsters/giant-fire-beetle",
    },
    {
      index: "giant-frog",
      name: "Giant Frog",
      url: "/api/monsters/giant-frog",
    },
    {
      index: "giant-goat",
      name: "Giant Goat",
      url: "/api/monsters/giant-goat",
    },
    {
      index: "giant-lizard",
      name: "Giant Lizard",
      url: "/api/monsters/giant-lizard",
    },
    { index: "giant-owl", name: "Giant Owl", url: "/api/monsters/giant-owl" },
    {
      index: "giant-poisonous-snake",
      name: "Giant Poisonous Snake",
      url: "/api/monsters/giant-poisonous-snake",
    },
    { index: "giant-rat", name: "Giant Rat", url: "/api/monsters/giant-rat" },
    {
      index: "giant-rat-diseased",
      name: "Giant Rat (Diseased)",
      url: "/api/monsters/giant-rat-diseased",
    },
    {
      index: "giant-sea-horse",
      name: "Giant Sea Horse",
      url: "/api/monsters/giant-sea-horse",
    },
    {
      index: "giant-wasp",
      name: "Giant Wasp",
      url: "/api/monsters/giant-wasp",
    },
    {
      index: "giant-weasel",
      name: "Giant Weasel",
      url: "/api/monsters/giant-weasel",
    },
    {
      index: "giant-wolf-spider",
      name: "Giant Wolf Spider",
      url: "/api/monsters/giant-wolf-spider",
    },
    { index: "gnoll", name: "Gnoll", url: "/api/monsters/gnoll" },
    { index: "goat", name: "Goat", url: "/api/monsters/goat" },
    { index: "goblin", name: "Goblin", url: "/api/monsters/goblin" },
    { index: "gray-ooze", name: "Gray Ooze", url: "/api/monsters/gray-ooze" },
    { index: "grimlock", name: "Grimlock", url: "/api/monsters/grimlock" },
    { index: "guard", name: "Guard", url: "/api/monsters/guard" },
    { index: "hawk", name: "Hawk", url: "/api/monsters/hawk" },
    { index: "hobgoblin", name: "Hobgoblin", url: "/api/monsters/hobgoblin" },
    {
      index: "homunculus",
      name: "Homunculus",
      url: "/api/monsters/homunculus",
    },
    { index: "hyena", name: "Hyena", url: "/api/monsters/hyena" },
    {
      index: "ice-mephit",
      name: "Ice Mephit",
      url: "/api/monsters/ice-mephit",
    },
    { index: "jackal", name: "Jackal", url: "/api/monsters/jackal" },
    { index: "kobold", name: "Kobold", url: "/api/monsters/kobold" },
    { index: "lemure", name: "Lemure", url: "/api/monsters/lemure" },
    { index: "lizard", name: "Lizard", url: "/api/monsters/lizard" },
    {
      index: "lizardfolk",
      name: "Lizardfolk",
      url: "/api/monsters/lizardfolk",
    },
    {
      index: "magma-mephit",
      name: "Magma Mephit",
      url: "/api/monsters/magma-mephit",
    },
    { index: "magmin", name: "Magmin", url: "/api/monsters/magmin" },
    { index: "mastiff", name: "Mastiff", url: "/api/monsters/mastiff" },
    { index: "merfolk", name: "Merfolk", url: "/api/monsters/merfolk" },
    { index: "mule", name: "Mule", url: "/api/monsters/mule" },
    { index: "noble", name: "Noble", url: "/api/monsters/noble" },
    { index: "octopus", name: "Octopus", url: "/api/monsters/octopus" },
    { index: "orc", name: "Orc", url: "/api/monsters/orc" },
    { index: "owl", name: "Owl", url: "/api/monsters/owl" },
    { index: "panther", name: "Panther", url: "/api/monsters/panther" },
    {
      index: "poisonous-snake",
      name: "Poisonous Snake",
      url: "/api/monsters/poisonous-snake",
    },
    { index: "pony", name: "Pony", url: "/api/monsters/pony" },
    {
      index: "pseudodragon",
      name: "Pseudodragon",
      url: "/api/monsters/pseudodragon",
    },
    { index: "quipper", name: "Quipper", url: "/api/monsters/quipper" },
    { index: "rat", name: "Rat", url: "/api/monsters/rat" },
    { index: "raven", name: "Raven", url: "/api/monsters/raven" },
    {
      index: "reef-shark",
      name: "Reef Shark",
      url: "/api/monsters/reef-shark",
    },
    {
      index: "riding-horse",
      name: "Riding Horse",
      url: "/api/monsters/riding-horse",
    },
    {
      index: "rust-monster",
      name: "Rust Monster",
      url: "/api/monsters/rust-monster",
    },
    { index: "sahuagin", name: "Sahuagin", url: "/api/monsters/sahuagin" },
    { index: "satyr", name: "Satyr", url: "/api/monsters/satyr" },
    { index: "scorpion", name: "Scorpion", url: "/api/monsters/scorpion" },
    { index: "scout", name: "Scout", url: "/api/monsters/scout" },
    { index: "sea-horse", name: "Sea Horse", url: "/api/monsters/sea-horse" },
    { index: "shadow", name: "Shadow", url: "/api/monsters/shadow" },
    { index: "shrieker", name: "Shrieker", url: "/api/monsters/shrieker" },
    { index: "skeleton", name: "Skeleton", url: "/api/monsters/skeleton" },
    { index: "spider", name: "Spider", url: "/api/monsters/spider" },
    { index: "sprite", name: "Sprite", url: "/api/monsters/sprite" },
    {
      index: "steam-mephit",
      name: "Steam Mephit",
      url: "/api/monsters/steam-mephit",
    },
    { index: "stirge", name: "Stirge", url: "/api/monsters/stirge" },
    {
      index: "swarm-of-bats",
      name: "Swarm of Bats",
      url: "/api/monsters/swarm-of-bats",
    },
    {
      index: "swarm-of-beetles",
      name: "Swarm of Beetles",
      url: "/api/monsters/swarm-of-beetles",
    },
    {
      index: "swarm-of-centipedes",
      name: "Swarm of Centipedes",
      url: "/api/monsters/swarm-of-centipedes",
    },
    {
      index: "swarm-of-insects",
      name: "Swarm of Insects",
      url: "/api/monsters/swarm-of-insects",
    },
    {
      index: "swarm-of-rats",
      name: "Swarm of Rats",
      url: "/api/monsters/swarm-of-rats",
    },
    {
      index: "swarm-of-ravens",
      name: "Swarm of Ravens",
      url: "/api/monsters/swarm-of-ravens",
    },
    {
      index: "swarm-of-spiders",
      name: "Swarm of Spiders",
      url: "/api/monsters/swarm-of-spiders",
    },
    {
      index: "swarm-of-wasps",
      name: "Swarm of Wasps",
      url: "/api/monsters/swarm-of-wasps",
    },
    { index: "thug", name: "Thug", url: "/api/monsters/thug" },
    {
      index: "tribal-warrior",
      name: "Tribal Warrior",
      url: "/api/monsters/tribal-warrior",
    },
    {
      index: "violet-fungus",
      name: "Violet Fungus",
      url: "/api/monsters/violet-fungus",
    },
    { index: "vulture", name: "Vulture", url: "/api/monsters/vulture" },
    { index: "warhorse", name: "Warhorse", url: "/api/monsters/warhorse" },
    {
      index: "warhorse-skeleton",
      name: "Warhorse Skeleton",
      url: "/api/monsters/warhorse-skeleton",
    },
    { index: "weasel", name: "Weasel", url: "/api/monsters/weasel" },
    { index: "wolf", name: "Wolf", url: "/api/monsters/wolf" },
    { index: "worg", name: "Worg", url: "/api/monsters/worg" },
    { index: "zombie", name: "Zombie", url: "/api/monsters/zombie" },
  ],
};

const imp = {
  index: "imp",
  name: "Imp",
  size: "Tiny",
  type: "fiend",
  subtype: "devil",
  alignment: "lawful evil",
  armor_class: 13,
  hit_points: 10,
  hit_dice: "3d4",
  speed: { walk: "20 ft.", fly: "40 ft." },
  strength: 6,
  dexterity: 17,
  constitution: 13,
  intelligence: 11,
  wisdom: 12,
  charisma: 14,
  proficiencies: [
    {
      value: 4,
      proficiency: {
        index: "skill-deception",
        name: "Skill: Deception",
        url: "/api/proficiencies/skill-deception",
      },
    },
    {
      value: 3,
      proficiency: {
        index: "skill-insight",
        name: "Skill: Insight",
        url: "/api/proficiencies/skill-insight",
      },
    },
    {
      value: 4,
      proficiency: {
        index: "skill-persuasion",
        name: "Skill: Persuasion",
        url: "/api/proficiencies/skill-persuasion",
      },
    },
    {
      value: 5,
      proficiency: {
        index: "skill-stealth",
        name: "Skill: Stealth",
        url: "/api/proficiencies/skill-stealth",
      },
    },
  ],
  damage_vulnerabilities: [],
  damage_resistances: [
    "cold",
    "bludgeoning, piercing, and slashing from nonmagical/nonsilver weapons",
  ],
  damage_immunities: ["fire", "poison"],
  condition_immunities: [
    { index: "poisoned", name: "Poisoned", url: "/api/conditions/poisoned" },
  ],
  senses: { darkvision: "120 ft.", passive_perception: 11 },
  languages: "Infernal, Common",
  challenge_rating: 1,
  xp: 200,
  special_abilities: [
    {
      name: "Shapechanger",
      desc: "The imp can use its action to polymorph into a beast form that resembles a rat (speed 20 ft.), a raven (20 ft., fly 60 ft.), or a spider (20 ft., climb 20 ft.), or back into its true form. Its statistics are the same in each form, except for the speed changes noted. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies.",
    },
    {
      name: "Devil's Sight",
      desc: "Magical darkness doesn't impede the imp's darkvision.",
    },
    {
      name: "Magic Resistance",
      desc: "The imp has advantage on saving throws against spells and other magical effects.",
    },
    {
      name: "Variant: Familiar",
      desc: "The imp can serve another creature as a familiar, forming a telepathic bond with its willing master. While the two are bonded, the master can sense what the quasit senses as long as they are within 1 mile of each other. While the imp is within 10 feet of its master, the master shares the quasit's Magic Resistance trait. At any time and for any reason, the imp can end its service as a familiar, ending the telepathic bond.",
    },
  ],
  actions: [
    {
      name: "Sting (Bite in Beast Form)",
      desc: "Melee Weapon Attack: +5 to hit, reach 5 ft ., one target. Hit: 5 (1d4 + 3) piercing damage, and the target must make on a DC 11 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much damage on a successful one.",
      attack_bonus: 5,
      damage: [
        {
          damage_type: {
            index: "piercing",
            name: "Piercing",
            url: "/api/damage-types/piercing",
          },
          damage_dice: "1d4+3",
        },
      ],
    },
    {
      name: "Invisibility",
      desc: "The imp magically turns invisible until it attacks, or until its concentration ends (as if concentrating on a spell). Any equipment the imp wears or carries is invisible with it.",
      damage: [],
    },
  ],
  url: "/api/monsters/imp",
};

const differentImp = {
  index: "imp",
  name: "Imp",
  size: "Tiny",
  type: "fiend",
  subtype: "devil",
  alignment: "lawful evil",
  armor_class: 13,
  hit_points: 10,
  hit_dice: "3d4",
  speed: { walk: "20 ft.", fly: "40 ft." },
  strength: 6,
  dexterity: 17,
  constitution: 13,
  intelligence: 11,
  wisdom: 12,
  charisma: 14,
  proficiencies: [
    { name: "Deception", stat: "Charisma" },
    { name: "Insight", stat: "Wisdom" },
    { name: "Persuasion", stat: "Charisma" },
    { name: "Stealth", stat: "Dexterity" },
  ],
  damage_vulnerabilities: [],
  damage_resistances: [
    "cold",
    "bludgeoning, piercing, and slashing from nonmagical/nonsilver weapons",
  ],
  damage_immunities: ["fire", "poison"],
  condition_immunities: [
    { index: "poisoned", name: "Poisoned", url: "/api/conditions/poisoned" },
  ],
  senses: { darkvision: "120 ft.", passive_perception: 11 },
  languages: "Infernal, Common",
  challenge_rating: 1,
  xp: 200,
  special_abilities: [
    {
      name: "Shapechanger",
      desc: "The imp can use its action to polymorph into a beast form that resembles a rat (speed 20 ft.), a raven (20 ft., fly 60 ft.), or a spider (20 ft., climb 20 ft.), or back into its true form. Its statistics are the same in each form, except for the speed changes noted. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies.",
    },
    {
      name: "Devil's Sight",
      desc: "Magical darkness doesn't impede the imp's darkvision.",
    },
    {
      name: "Magic Resistance",
      desc: "The imp has advantage on saving throws against spells and other magical effects.",
    },
    {
      name: "Variant: Familiar",
      desc: "The imp can serve another creature as a familiar, forming a telepathic bond with its willing master. While the two are bonded, the master can sense what the quasit senses as long as they are within 1 mile of each other. While the imp is within 10 feet of its master, the master shares the quasit's Magic Resistance trait. At any time and for any reason, the imp can end its service as a familiar, ending the telepathic bond.",
    },
  ],
  actions: [
    {
      name: "Sting (Bite in Beast Form)",
      desc: "Melee Weapon Attack: +5 to hit, reach 5 ft ., one target. Hit: 5 (1d4 + 3) piercing damage, and the target must make on a DC 11 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much damage on a successful one.",
      attack_bonus: 5,
      damage: [
        {
          damage_type: {
            index: "piercing",
            name: "Piercing",
            url: "/api/damage-types/piercing",
          },
          damage_dice: "1d4+3",
        },
      ],
    },
    {
      name: "Invisibility",
      desc: "The imp magically turns invisible until it attacks, or until its concentration ends (as if concentrating on a spell). Any equipment the imp wears or carries is invisible with it.",
      damage: [],
    },
  ],
  url: "/api/monsters/imp",
};

const aboleth = {
  index: "aboleth",
  name: "Aboleth",
  size: "Large",
  type: "aberration",
  subtype: null,
  alignment: "lawful evil",
  armor_class: 17,
  hit_points: 135,
  hit_dice: "18d10",
  speed: { walk: "10 ft.", swim: "40 ft." },
  strength: 21,
  dexterity: 9,
  constitution: 15,
  intelligence: 18,
  wisdom: 15,
  charisma: 18,
  proficiencies: [
    {
      value: 6,
      proficiency: {
        index: "saving-throw-con",
        name: "Saving Throw: CON",
        url: "/api/proficiencies/saving-throw-con",
      },
    },
    {
      value: 8,
      proficiency: {
        index: "saving-throw-int",
        name: "Saving Throw: INT",
        url: "/api/proficiencies/saving-throw-int",
      },
    },
    {
      value: 6,
      proficiency: {
        index: "saving-throw-wis",
        name: "Saving Throw: WIS",
        url: "/api/proficiencies/saving-throw-wis",
      },
    },
    {
      value: 12,
      proficiency: {
        index: "skill-history",
        name: "Skill: History",
        url: "/api/proficiencies/skill-history",
      },
    },
    {
      value: 10,
      proficiency: {
        index: "skill-perception",
        name: "Skill: Perception",
        url: "/api/proficiencies/skill-perception",
      },
    },
  ],
  damage_vulnerabilities: [],
  damage_resistances: [],
  damage_immunities: [],
  condition_immunities: [],
  senses: { darkvision: "120 ft.", passive_perception: 20 },
  languages: "Deep Speech, telepathy 120 ft.",
  challenge_rating: 10,
  xp: 5900,
  special_abilities: [
    { name: "Amphibious", desc: "The aboleth can breathe air and water." },
    {
      name: "Mucous Cloud",
      desc: "While underwater, the aboleth is surrounded by transformative mucus. A creature that touches the aboleth or that hits it with a melee attack while within 5 ft. of it must make a DC 14 Constitution saving throw. On a failure, the creature is diseased for 1d4 hours. The diseased creature can breathe only underwater.",
      dc: {
        dc_type: { index: "con", name: "CON", url: "/api/ability-scores/con" },
        dc_value: 14,
        success_type: "none",
      },
    },
    {
      name: "Probing Telepathy",
      desc: "If a creature communicates telepathically with the aboleth, the aboleth learns the creature's greatest desires if the aboleth can see the creature.",
    },
  ],
  actions: [
    {
      name: "Multiattack",
      desc: "The aboleth makes three tentacle attacks.",
      options: {
        choose: 1,
        from: [[{ name: "Tentacle", count: 3, type: "melee" }]],
      },
      damage: [],
    },
    {
      name: "Tentacle",
      desc: "Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 12 (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased. The disease has no effect for 1 minute and can be removed by any magic that cures disease. After 1 minute, the diseased creature's skin becomes translucent and slimy, the creature can't regain hit points unless it is underwater, and the disease can be removed only by heal or another disease-curing spell of 6th level or higher. When the creature is outside a body of water, it takes 6 (1d12) acid damage every 10 minutes unless moisture is applied to the skin before 10 minutes have passed.",
      attack_bonus: 9,
      dc: {
        dc_type: { index: "con", name: "CON", url: "/api/ability-scores/con" },
        dc_value: 14,
        success_type: "none",
      },
      damage: [
        {
          damage_type: {
            index: "acid",
            name: "Acid",
            url: "/api/damage-types/acid",
          },
          damage_dice: "2d6+5",
        },
      ],
    },
    {
      name: "Tail",
      desc: "Melee Weapon Attack: +9 to hit, reach 10 ft. one target. Hit: 15 (3d6 + 5) bludgeoning damage.",
      attack_bonus: 9,
      damage: [
        {
          damage_type: {
            index: "bludgeoning",
            name: "Bludgeoning",
            url: "/api/damage-types/bludgeoning",
          },
          damage_dice: "3d6+5",
        },
      ],
    },
    {
      name: "Enslave",
      desc: "The aboleth targets one creature it can see within 30 ft. of it. The target must succeed on a DC 14 Wisdom saving throw or be magically charmed by the aboleth until the aboleth dies or until it is on a different plane of existence from the target. The charmed target is under the aboleth's control and can't take reactions, and the aboleth and the target can communicate telepathically with each other over any distance.\nWhenever the charmed target takes damage, the target can repeat the saving throw. On a success, the effect ends. No more than once every 24 hours, the target can also repeat the saving throw when it is at least 1 mile away from the aboleth.",
      usage: { type: "per day", times: 3 },
      dc: {
        dc_type: { index: "wis", name: "WIS", url: "/api/ability-scores/wis" },
        dc_value: 14,
        success_type: "none",
      },
      damage: [],
    },
  ],
  legendary_actions: [
    { name: "Detect", desc: "The aboleth makes a Wisdom (Perception) check." },
    { name: "Tail Swipe", desc: "The aboleth makes one tail attack." },
    {
      name: "Psychic Drain (Costs 2 Actions)",
      desc: "One creature charmed by the aboleth takes 10 (3d6) psychic damage, and the aboleth regains hit points equal to the damage the creature takes.",
      attack_bonus: 0,
      damage: [
        {
          damage_type: {
            index: "psychic",
            name: "Psychic",
            url: "/api/damage-types/psychic",
          },
          damage_dice: "3d6",
        },
      ],
    },
  ],
  url: "/api/monsters/aboleth",
};
